### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by johnakisk0700** [g0d/GreyOS#4]
Instructions were pretty unclear, I flashed this on a USB using Rufus and the bootloader straight ignores it. I use arch btw.

**Comment by g0d** [comment]
Hi John, I don't believe we have any instructions for the Meta-USB. So, I guess you tried this somehow with yourself...
It's logical that nothing works as Arch Linux is not the way to go.

It is a difficult process to create a bootable custom distro indeed so I will provide a ready ISO for anybody to burn in a USB. This ISO will be updated over the years to reflect the most recent upgrades. In the meantime, we will add documentation.

So it is logical you faced issues.

Thanks for pointing this out. I will update you soon!

**Comment by johnakisk0700** [comment]
Ok, I'm sorry I saw the "OS" in the name and got carried away. 

I now realize my mistake, it wasn't a regular OS but a web one 😅😅😅

So how do I run this with Apache on Ubuntu? I tried

**Comment by g0d** [comment]
Hello dear Giannis,

One of my partners is getting ready a very straightforward documentation for the installation process. 
I will share when all is good!

In the meantime for you to play, there is no really need for MySQL or such DBs. Just put the contents of the Code folder in the root folder (htdocs) of a typical XAMPP installation, hit run and play. That's all!

Best,
George.

**Comment by g0d** [comment]
Dear Giannis,

Check the description. I have updated everything so that you can download the ISO and burn it to a USB.

Happy Meta-Hacking!

:)

G.D.
