### ISSUE TITLE
How does Coyote work?

### ISSUE THREAD

**Issue by Aethedor** [g0d/GreyOS#5]
Hi. Cool project. I'm trying to understand how the Coyote browser works. It looks like the remote webpage is converted to a video tag. How does that work?? I'm also struggling to find the right PHP code which loads the remote website. The routing inside the code is not very clear to me. The Edge developer tools doesn't show any network activity when I click in side a page inside Coyote, so I don't know what request is being send.

**Comment by g0d** [comment]
It is a virtualized docker in remote server.
