### ISSUE TITLE
GreyOS hypervisor crashes when I try to run Doom

### ISSUE THREAD

**Issue by zimNMM** [g0d/GreyOS#6]
Issue description: Hi, I'm a gamer and I wanted to play Doom on your OS. But I ran into a problem. Your hypervisor crashes every time I try to run the game. It gives me an error message that says "Uncaught TypeError: Cannot read property 'shoot' of undefined". I don't know what that means, but it sounds bad. Please fix this issue as soon as possible, because I really want to play Doom on your OS. Thanks.

P.S. Why are you using JavaScript to write a hypervisor? That's like using a spoon to dig a tunnel. It doesn't make any sense. You should use a lower-level language, like Assembly or C, to write a hypervisor. You can read more about why JavaScript is not suitable for hypervisors here: https://stackoverflow.com/questions/12345678/why-is-javascript-not-suitable-for-hypervisors

**Comment by zisoszv** [comment]
Please reopen. Needs to be fixed. I will push the fix.

**Comment by g0d** [comment]
SPAMMERS
