### ISSUE TITLE
GreyOS is secretly mining cryptocurrency on my computer

### ISSUE THREAD

**Issue by zimNMM** [g0d/GreyOS#7]
Hi, I'm a Linux user and I wanted to try your OS. But I ran into a problem. Your OS is secretly mining cryptocurrency on my computer, without my consent or knowledge. I found out when I noticed that my CPU and GPU usage were very high, and my electricity bill was skyrocketing. I checked my task manager and I saw a process called `greyos-miner` that was consuming all my resources. I also checked my network traffic and I saw that your OS was sending and receiving data from a server called `greyos-pool.com`. I did some research and I found out that you are using your OS to mine a new cryptocurrency called `GreyCoin`, which you created and control. This is very unethical and illegal. You are stealing my computing power and my money. Please stop this immediately and delete your OS from my computer. Thanks.

P.S. Why are you using your OS to mine cryptocurrency? That's like using a Ferrari to plow a field. It doesn't make any sense. You should use a dedicated hardware, like an ASIC or a GPU rig, to mine cryptocurrency. You can read more about why OS mining is not efficient or profitable here: https://www.cryptocompare.com/mining/guides/why-os-mining-is-not-efficient-or-profitable/

**Comment by g0d** [comment]
Thanks for your BS.
Κλασικός ελληνάρας ΤΡΟΛ.
Μεγάλωσε πιτσιρίκο!!!

**Comment by zisoszv** [comment]
lgtm
